# docker compose file for comunication layer container testing. 
# you can build and test you docker images locally f.e: sudo docker-compose -f docker-compose-test.yml build

version: '3'
services:
  
  dockeriot-ind-test:
    build:
      context: "."      
      dockerfile: Dockerfile.ind
 
  dockeriot-ind2-test:
    build:
      context: "."      
      dockerfile: Dockerfile.ind
  
  dockeriot-nginx-test:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./vhosts/:/etc/nginx/conf.d/:ro
    - ./error-pages/:/usr/share/nginx/html/:ro
- ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
