# docker compose file for flask microservice that expose sensor/actuator data.

version: '3'
services:

  dockeriot-sensor:
    build:
      context: "."
      dockerfile: senact.Dockerfile

  dockeriot-actuator:
    build:
      context: "."
      dockerfile: senact.Dockerfile

  dockeriot-nginx-test:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./vhosts/:/etc/nginx/conf.d/:ro
    - ./error-pages/:/usr/share/nginx/html/:ro
- ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
